<a href="https://colab.research.google.com/github/detoma2158208-bit/progetto-intelligenza-artificiale-/blob/main/progetto_ia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dataset_path= "/content/drive/MyDrive/datasets (1)/"
df= pd.read_csv(dataset_path  + 'data.csv', index_col=None,header=0)
df.head()

,gender,C_api,C_man,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,...,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
0,1,male,1,2,2,20170527205915,20170721044501,543,56,43,...,4,0,0,91,28,6,76,324,0.915024,978
1,0,unknown,3,3,1,20110301072441,20170731213735,2764,2345,514,...,7,0,0,100,249,183,646,1526,0.661673,477
2,1,male,1,0,2,20060907204302,20140911191722,57,2927,25,...,0,0,0,3,0,1,3,49,0.800528,664
3,1,male,1,1,2,20121003144916,20121208180528,104,67,5,...,2,0,0,20,1,2,2,78,1.027717,841
4,0,unknown,3,1,1,20070311125035,20141106121057,184,2798,27,...,0,0,0,26,10,5,24,112,0.997535,994

In [ ]:
df.shape

(4746, 21)

In [ ]:
df.dtypes

gender             int64
C_api             object
C_man              int64
E_NEds             int64
E_Bpag             int64
firstDay           int64
lastDay            int64
NEds               int64
NDays              int64
NActDays           int64
NPages             int64
NPcreated          int64
pagesWomen         int64
wikiprojWomen      int64
ns_user            int64
ns_wikipedia       int64
ns_talk            int64
ns_userTalk        int64
ns_content         int64
weightIJ         float64
NIJ                int64
dtype: object

In [ ]:
df['gender'].value_counts()
#(normalize=True)

gender
1    2792
0    1601
2     353
Name: count, dtype: int64

In [ ]:
df['C_man'].value_counts()

C_man
3    2422
1    2029
2     295
Name: count, dtype: int64

vediamo come il due, che corrisponde al valore female, risulta minore degli altri valori. Il dataset può quindi essere definito come sbilanciato verso le classi 0 e 1

In [ ]:
df['gender'].value_counts()

gender
1    2792
0    1601
2     353
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         4746 non-null   int64
 1   C_api          4746 non-null   object
 2   C_man          4746 non-null   int64
 3   E_NEds         4746 non-null   int64
 4   E_Bpag         4746 non-null   int64
 5   firstDay       4746 non-null   int64
 6   lastDay        4746 non-null   int64
 7   NEds           4746 non-null   int64
 8   NDays          4746 non-null   int64
 9   NActDays       4746 non-null   int64
 10  NPages         4746 non-null   int64
 11  NPcreated      4746 non-null   int64
 12  pagesWomen     4746 non-null   int64
 13  wikiprojWomen  4746 non-null   int64
 14  ns_user        4746 non-null   int64
 15  ns_wikipedia   4746 non-null   int64
 16  ns_talk        4746 non-null   int64
 17  ns_userTalk    4746 non-null   int64
 18  ns_content     4746 non-null   int64
 19  weightIJ       4746 non-null   float64
 20  NIJ            4746 non-null   int64
dtypes: float64(1), int64(19), object(1)
memory usage: 778.8+ KB

In [ ]:
df.isnull().sum()

gender           0
C_api            0
C_man            0
E_NEds           0
E_Bpag           0
firstDay         0
lastDay          0
NEds             0
NDays            0
NActDays         0
NPages           0
NPcreated        0
pagesWomen       0
wikiprojWomen    0
ns_user          0
ns_wikipedia     0
ns_talk          0
ns_userTalk      0
ns_content       0
weightIJ         0
NIJ              0
dtype: int64

In [ ]:
df.describe()

,gender,C_man,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,NPages,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
count,4746.000000,4746.000000,4746.000000,4746.000000,4746,4.746000e+03,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000,4746.000000
mean,0.737042,2.082807,1.484197,1.646228,2010-05-16 01:58:44.594184704,2.015489e+13,2029.969448,2036.607880,183.162663,689.451960,43.479140,0.438896,0.439949,74.372946,74.368310,49.947745,96.081753,1521.886641,1.000000,867.148546
min,0.000000,1.000000,0.000000,0.000000,2002-01-14 16:37:35,2.012010e+13,50.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.411985,297.000000
25%,0.000000,1.000000,1.000000,1.000000,2007-04-21 14:49:14,2.014070e+13,95.000000,835.250000,24.000000,29.000000,1.000000,0.000000,0.000000,4.000000,0.000000,0.000000,1.000000,61.000000,0.831954,664.000000
50%,1.000000,3.000000,1.000000,2.000000,2009-12-09 09:27:17,2.016072e+13,218.000000,2035.500000,53.000000,68.000000,4.000000,0.000000,0.000000,14.000000,1.000000,4.000000,5.000000,151.000000,0.997535,917.000000
75%,1.000000,3.000000,2.000000,3.000000,2013-04-05 03:02:26.500000,2.017073e+13,757.750000,3146.500000,154.000000,219.750000,14.000000,0.000000,0.000000,46.000000,8.000000,19.000000,22.000000,563.750000,1.057149,994.000000
max,2.000000,3.000000,3.000000,3.000000,2017-09-29 21:50:32,2.017100e+13,153193.000000,5349.000000,3843.000000,94142.000000,13394.000000,185.000000,949.000000,6041.000000,24392.000000,4788.000000,12350.000000,115547.000000,1.865008,1596.000000
std,0.585355,0.964978,1.099795,1.079263,NaN,1.748104e+10,7793.300833,1336.119914,374.034481,3355.302483,297.395507,5.327440,17.832244,246.407233,560.782479,215.554281,545.025818,6099.009235,0.325763,325.933076

In [ ]:
df['firstDay'] = pd.to_datetime(df['firstDay'].astype(str), format='%Y%m%d%H%M%S')
df.head()

,gender,C_api,C_man,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,...,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
0,1,male,1,2,2,2017-05-27 20:59:15,20170721044501,543,56,43,...,4,0,0,91,28,6,76,324,0.915024,978
1,0,unknown,3,3,1,2011-03-01 07:24:41,20170731213735,2764,2345,514,...,7,0,0,100,249,183,646,1526,0.661673,477
2,1,male,1,0,2,2006-09-07 20:43:02,20140911191722,57,2927,25,...,0,0,0,3,0,1,3,49,0.800528,664
3,1,male,1,1,2,2012-10-03 14:49:16,20121208180528,104,67,5,...,2,0,0,20,1,2,2,78,1.027717,841
4,0,unknown,3,1,1,2007-03-11 12:50:35,20141106121057,184,2798,27,...,0,0,0,26,10,5,24,112,0.997535,994

In [ ]:
df['lastDay'] = pd.to_datetime(df['lastDay'].astype(str), format='%Y%m%d%H%M%S')
df.head()

,gender,C_api,C_man,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,...,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
0,1,male,1,2,2,2017-05-27 20:59:15,2017-07-21 04:45:01,543,56,43,...,4,0,0,91,28,6,76,324,0.915024,978
1,0,unknown,3,3,1,2011-03-01 07:24:41,2017-07-31 21:37:35,2764,2345,514,...,7,0,0,100,249,183,646,1526,0.661673,477
2,1,male,1,0,2,2006-09-07 20:43:02,2014-09-11 19:17:22,57,2927,25,...,0,0,0,3,0,1,3,49,0.800528,664
3,1,male,1,1,2,2012-10-03 14:49:16,2012-12-08 18:05:28,104,67,5,...,2,0,0,20,1,2,2,78,1.027717,841
4,0,unknown,3,1,1,2007-03-11 12:50:35,2014-11-06 12:10:57,184,2798,27,...,0,0,0,26,10,5,24,112,0.997535,994

In [ ]:
df.dtypes

gender                    int64
C_api                    object
C_man                     int64
E_NEds                    int64
E_Bpag                    int64
firstDay         datetime64[ns]
lastDay          datetime64[ns]
NEds                      int64
NDays                     int64
NActDays                  int64
NPages                    int64
NPcreated                 int64
pagesWomen                int64
wikiprojWomen             int64
ns_user                   int64
ns_wikipedia              int64
ns_talk                   int64
ns_userTalk               int64
ns_content                int64
weightIJ                float64
NIJ                       int64
dtype: object

eliminiamo due colonne che non ci servono

In [ ]:
df2=df.drop(columns=['C_api','C_man'])
df2.head()

,gender,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,NPages,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
0,1,2,2,2017-05-27 20:59:15,2017-07-21 04:45:01,543,56,43,204,4,0,0,91,28,6,76,324,0.915024,978
1,0,3,1,2011-03-01 07:24:41,2017-07-31 21:37:35,2764,2345,514,722,7,0,0,100,249,183,646,1526,0.661673,477
2,1,0,2,2006-09-07 20:43:02,2014-09-11 19:17:22,57,2927,25,25,0,0,0,3,0,1,3,49,0.800528,664
3,1,1,2,2012-10-03 14:49:16,2012-12-08 18:05:28,104,67,5,66,2,0,0,20,1,2,2,78,1.027717,841
4,0,1,1,2007-03-11 12:50:35,2014-11-06 12:10:57,184,2798,27,125,0,0,0,26,10,5,24,112,0.997535,994

ora vogliamo costruire due dataset: uno con 0 e uno con 1 e 2

In [ ]:
df2_unknown= df2[df2['gender']==0].copy()
df2_unknown.head()

,gender,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,NPages,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
1,0,3,1,2011-03-01 07:24:41,2017-07-31 21:37:35,2764,2345,514,722,7,0,0,100,249,183,646,1526,0.661673,477
4,0,1,1,2007-03-11 12:50:35,2014-11-06 12:10:57,184,2798,27,125,0,0,0,26,10,5,24,112,0.997535,994
6,0,0,1,2013-07-22 23:41:49,2013-07-31 13:06:29,57,10,7,13,1,0,0,10,0,4,6,37,1.057149,1074
10,0,1,3,2011-05-10 15:53:59,2016-09-21 11:24:01,160,1962,40,42,0,0,0,36,0,34,28,60,0.594368,493
14,0,0,2,2010-10-13 09:16:09,2015-07-27 12:18:54,81,1749,38,34,0,0,0,33,0,0,0,30,0.800528,664

In [ ]:
#1=male e 2=female
df2_known= df2[df2['gender'].isin([1,2])].copy()
df2_known.head(100)

,gender,E_NEds,E_Bpag,firstDay,lastDay,NEds,NDays,NActDays,NPages,NPcreated,pagesWomen,wikiprojWomen,ns_user,ns_wikipedia,ns_talk,ns_userTalk,ns_content,weightIJ,NIJ
0,1,2,2,2017-05-27 20:59:15,2017-07-21 04:45:01,543,56,43,204,4,0,0,91,28,6,76,324,0.915024,978
2,1,0,2,2006-09-07 20:43:02,2014-09-11 19:17:22,57,2927,25,25,0,0,0,3,0,1,3,49,0.800528,664
3,1,1,2,2012-10-03 14:49:16,2012-12-08 18:05:28,104,67,5,66,2,0,0,20,1,2,2,78,1.027717,841
5,1,3,1,2006-05-26 14:19:42,2017-09-14 13:19:32,1887,4130,197,510,62,0,0,7,2,31,10,1660,0.661673,477
7,1,3,3,2008-11-05 22:48:14,2017-08-18 01:29:59,5833,3209,566,376,108,0,0,161,10,9,184,4744,1.481654,1596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,1,1,2,2011-04-05 14:10:56,2017-08-20 21:43:28,121,2330,37,57,1,0,0,30,6,8,2,57,1.027717,841
158,2,1,1,2016-10-20 07:55:33,2017-05-15 18:49:17,109,208,19,9,0,0,0,91,0,1,13,4,0.997535,994
159,2,0,0,2005-05-23 11:01:05,2012-05-27 18:22:51,88,2562,15,11,2,0,0,2,0,1,2,83,1.865008,1277
160,1,0,3,2017-02-04 14:14:33,2017-02-06 18:04:26,61,3,3,3,1,0,0,60,0,0,0,1,0.411985,297
161,1,3,3,2008-02-26 21:28:44,2017-07-15 13:39:49,2853,3428,413,1031,37,1,0,128,82,159,218,1354,1.481654,1596

creo x e y per known

In [ ]:
y= df2_known['gender']
X= df2_known.drop(columns=['gender'])
y.head(100)

0      1
2      1
3      1
5      1
7      1
      ..
157    1
158    2
159    2
160    1
161    1
Name: gender, Length: 100, dtype: int64